version: "3"

services:
  web:
    build:
      dockerfile: Dockerfile
    image: php:8.1.10-apache
    restart: 'on-failure:3'
    ports:
      - '8080:80'
    links:
      - mariadb
    depends_on:
      - mariadb
    volumes: 
      - ./htdocs:/var/www/html/
    exec: "php migrations.php"
  mariadb:
    image: mariadb:10.9.2
    restart: 'always'
    volumes: 
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "wwi2021a"
      MYSQL_DATABASE: "wwi2021a"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "wwi2021a"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    links:
      - mariadb
    depends_on:
      - mariadb      
    environment:
      - PMA_ARBITRARY=1      